### ISSUE TITLE
Problem with processing BIGINT values

### ISSUE THREAD

**Issue by pahan35** [mlaanderson/database-js-mysql#2]
I noticed that we can't correctly fetch BIGINT values from DB. It is regular problem of **mysql** package.

It can be fixed using advice from [this answer](https://stackoverflow.com/a/28759492/6625548)

```
const connectionOptions = {...};//previous connection options
Object.assign(connectionOptions, {supportBigNumbers: true, bigNumberStrings: true})
var connection = mysql.createConnection(connectionOptions);
```

Maybe we should add this options only on some conditions or by other logic.

Please select the way of fixing it and I can make PR

**Comment by mlaanderson** [comment]
Sorry for the late response, my paying gig and my house pulled me away.

The MySQL driver for database-js needs to be made to accept parameters, then those options can be chosen by the user.

The url format is:
driver://user:password@host:port/database?param1=value1&param2=value2&...

The parameters are a string, but if you call parseParameters on the connection object passed to the open function in the MySQL driver it will return a JSON object. However, every value in that JSON object will still be strings. It could be helpful to have a conversion function that will convert valid MySQL options to their Javascript types.

Then the user will pass the url:
mysql://user:password@host/database?supportBigNumbers=true&bigNumberStrings=true

**Comment by mlaanderson** [comment]
The list of connection options is available here: https://www.npmjs.com/package/mysql#connection-options

**Comment by mlaanderson** [comment]
Please be sure to use spaces instead of tabs in your code. I have no preference, but since we've started with spaces we avoid unnecessary diffs based on whitespace if we stick with spaces.

**Comment by pahan35** [comment]
@mlaanderson thanks for the response. I see that these params are passed to the database-js-mysql constructor, but they are skipped during connection init.

Have you any implemented example of passing similar options to other database-js DB drivers?

**Comment by pahan35** [comment]
@mlaanderson I've gone through your database-js-* projects and found that there are several implementations of the required feature:
1.  appropriate in [database-js-csv](https://github.com/mlaanderson/database-js-csv/blob/master/index.js)
2. this implementation in [database-js-firebase](https://github.com/mlaanderson/database-js-firebase/blob/master/index.js) can be replaced by first implementation.

Maybe it's better to move parse parameter logic to separate module and use its logic where we wanna add extra params?

**Comment by mlaanderson** [comment]
That’s a pretty good idea. Right now it’s in the connection object under database-js, but making a utility module makes sense.

**Comment by mlaanderson** [comment]
I’ve created an empty repository called database-js-common for this purpose.
https://github.com/mlaanderson/database-js-common

Right now it has no content. Feel free to contribute if you’d like.

**Comment by pahan35** [comment]
I'm gonna create index.js with exported method **parseParamsString**.

Have you any preferences about naming conventions of exported methods and common code structure? Maybe you can provide links to your best-practices repositories?

**Comment by mlaanderson** [comment]
Thank you for the patch Pavlo.
